export type Country = { name: string; lat: number; lon: number };
export type CountryGroup = { label: string; countries: Country[] };

export const COUNTRY_GROUPS: CountryGroup[] = [
  {
    label: "Afrique du Nord",
    countries: [
      { name: "Maroc", lat: 31.8, lon: -7.1 },
      { name: "Algérie", lat: 28.0, lon: 1.7 },
      { name: "Tunisie", lat: 33.9, lon: 9.5 },
      { name: "Libye", lat: 26.3, lon: 17.2 },
      { name: "Égypte", lat: 26.8, lon: 30.8 },
      { name: "Soudan", lat: 15.6, lon: 30.2 },
      { name: "Soudan du Sud", lat: 7.9, lon: 31.3 },
      { name: "Mauritanie", lat: 21.0, lon: -10.9 },
    ],
  },
  {
    label: "Afrique de l'Ouest",
    countries: [
      { name: "Sénégal", lat: 14.5, lon: -14.5 },
      { name: "Gambie", lat: 13.4, lon: -15.3 },
      { name: "Guinée-Bissau", lat: 11.9, lon: -15.6 },
      { name: "Guinée", lat: 10.4, lon: -10.9 },
      { name: "Sierra Leone", lat: 8.6, lon: -11.8 },
      { name: "Liberia", lat: 6.4, lon: -9.4 },
      { name: "Côte d'Ivoire", lat: 7.5, lon: -5.5 },
      { name: "Ghana", lat: 7.9, lon: -1.0 },
      { name: "Togo", lat: 8.6, lon: 0.8 },
      { name: "Bénin", lat: 9.3, lon: 2.3 },
      { name: "Burkina Faso", lat: 12.2, lon: -1.6 },
      { name: "Mali", lat: 17.6, lon: -4.0 },
      { name: "Niger", lat: 17.6, lon: 8.1 },
      { name: "Nigeria", lat: 9.1, lon: 8.7 },
    ],
  },
  {
    label: "Afrique centrale",
    countries: [
      { name: "Cameroun", lat: 5.7, lon: 12.7 },
      { name: "Centrafrique", lat: 6.6, lon: 20.9 },
      { name: "Tchad", lat: 15.5, lon: 18.7 },
      { name: "Guinée équatoriale", lat: 1.7, lon: 10.5 },
      { name: "Gabon", lat: -0.8, lon: 11.6 },
      { name: "République du Congo", lat: -0.7, lon: 15.4 },
      { name: "RD Congo", lat: -2.9, lon: 23.6 },
      { name: "Angola", lat: -11.2, lon: 17.9 },
    ],
  },
  {
    label: "Afrique de l'Est",
    countries: [
      { name: "Éthiopie", lat: 9.1, lon: 40.5 },
      { name: "Érythrée", lat: 15.2, lon: 39.8 },
      { name: "Djibouti", lat: 11.8, lon: 43.2 },
      { name: "Somalie", lat: 5.2, lon: 46.2 },
      { name: "Kenya", lat: 0.2, lon: 37.9 },
      { name: "Ouganda", lat: 1.4, lon: 32.3 },
      { name: "Rwanda", lat: -1.9, lon: 29.9 },
      { name: "Burundi", lat: -3.4, lon: 29.9 },
      { name: "Tanzanie", lat: -6.4, lon: 34.9 },
    ],
  },
  {
    label: "Afrique australe",
    countries: [
      { name: "Zambie", lat: -13.1, lon: 27.8 },
      { name: "Malawi", lat: -13.3, lon: 34.3 },
      { name: "Mozambique", lat: -18.7, lon: 35.5 },
      { name: "Zimbabwe", lat: -19.0, lon: 29.2 },
      { name: "Botswana", lat: -22.3, lon: 24.7 },
      { name: "Namibie", lat: -22.9, lon: 18.5 },
      { name: "Afrique du Sud", lat: -29.0, lon: 25.1 },
      { name: "Lesotho", lat: -29.6, lon: 28.2 },
      { name: "Eswatini", lat: -26.5, lon: 31.5 },
    ],
  },
  {
    label: "Îles & océan Indien",
    countries: [
      { name: "Madagascar", lat: -19.4, lon: 46.7 },
      { name: "Maurice", lat: -20.3, lon: 57.6 },
      { name: "Seychelles", lat: -4.7, lon: 55.5 },
      { name: "Comores", lat: -11.6, lon: 43.3 },
      { name: "Cap-Vert", lat: 15.1, lon: -23.6 },
      { name: "Sao Tomé-et-Principe", lat: 0.2, lon: 6.6 },
      { name: "Réunion", lat: -21.1, lon: 55.5 },
      { name: "Mayotte", lat: -12.8, lon: 45.2 },
    ],
  },
  {
    label: "Antilles & Guyanes",
    countries: [
      { name: "Guadeloupe", lat: 16.2, lon: -61.6 },
      { name: "Martinique", lat: 14.6, lon: -61.0 },
      { name: "Guyane", lat: 4.0, lon: -53.2 },
      { name: "Haïti", lat: 18.9, lon: -72.3 },
      { name: "République dominicaine", lat: 18.7, lon: -70.2 },
      { name: "Cuba", lat: 21.5, lon: -77.8 },
      { name: "Jamaïque", lat: 18.1, lon: -77.3 },
      { name: "Trinité-et-Tobago", lat: 10.4, lon: -61.3 },
      { name: "Barbade", lat: 13.2, lon: -59.5 },
      { name: "Sainte-Lucie", lat: 13.9, lon: -60.9 },
      { name: "Saint-Martin", lat: 18.1, lon: -63.0 },
    ],
  },
  {
    label: "Diaspora & autres",
    countries: [
      { name: "France", lat: 46.6, lon: 2.2 },
      { name: "Belgique", lat: 50.5, lon: 4.5 },
      { name: "Suisse", lat: 46.8, lon: 8.2 },
      { name: "Canada", lat: 56.1, lon: -106.3 },
      { name: "États-Unis", lat: 39.8, lon: -98.6 },
      { name: "Royaume-Uni", lat: 54.0, lon: -2.5 },
      { name: "Allemagne", lat: 51.1, lon: 10.4 },
      { name: "Espagne", lat: 40.4, lon: -3.7 },
      { name: "Portugal", lat: 39.4, lon: -8.2 },
      { name: "Italie", lat: 41.9, lon: 12.6 },
      { name: "Pays-Bas", lat: 52.1, lon: 5.3 },
    ],
  },
];

export const ALL_COUNTRIES: Country[] = COUNTRY_GROUPS.flatMap((g) => g.countries);