import type { Theme } from "./types";

// Plan BUSINESS : bannières avec visuels (image ou mockup produit), couvertures,
// et profils riches (blocs stats / FAQ / à propos).
export const BUSINESS_THEMES: Theme[] = [
  {
    // Modèle 1 : barbier, noir et cuivre doré, bannières encadrées
    id: "barbier",
    name: "Barbier",
    plan: "business",
    layout: "banners",
    buttonStyle: "soft",
    header: "cover",
    avatarShape: "rounded",
    dark: true,
    uppercaseLinks: true,
    tracking: "0.08em",
    fonts: ["Playfair+Display:wght@500;600;700", "Montserrat:wght@400;500;600;700"],
    tokens: {
      bg: "radial-gradient(circle at 50% 0%,#3A2A12 0%,#0D0B08 45%,#050403 100%)",
      surface: "#14110D",
      text: "#F4E9D6",
      muted: "#B9A88A",
      accent: "#D9A850",
      accent2: "#8A5E1F",
      onAccent: "#1A1204",
      border: "#C79A55",
      radius: "16px",
      shadow: "none",
      headerBg: "linear-gradient(180deg,#4A3414,#0D0B08)",
      fontDisplay: "Playfair Display",
      fontBody: "Montserrat",
    },
  },
  {
    // Modèle 11 : infoproductrice, fond blanc, bannières or sable avec bouton blanc
    id: "infoproductrice",
    name: "Infoproductrice",
    plan: "business",
    layout: "banners",
    buttonStyle: "gradient",
    header: "center",
    avatarShape: "circle",
    dark: false,
    fonts: ["Cormorant+Garamond:wght@500;600;700", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "#FFFFFF",
      surface: "#F7F3EC",
      text: "#2B2B2B",
      muted: "#7A6F5F",
      accent: "#B79C6B",
      accent2: "#9E8156",
      onAccent: "#FFFFFF",
      border: "#E9E1D2",
      radius: "8px",
      shadow: "none",
      headerBg: "#F7F3EC",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Poppins",
    },
  },
  {
    // Modèle 13 : or premium, fond dégradé blanc → or, bannières en verre doré
    id: "or-premium",
    name: "Or premium",
    plan: "business",
    layout: "banners",
    buttonStyle: "glass",
    header: "center",
    avatarShape: "circle",
    dark: false,
    fonts: ["Playfair+Display:wght@400;500;600;700", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "linear-gradient(180deg,#FFFFFF 0%,#F6EFE2 30%,#E3CB9A 65%,#B98B4E 100%)",
      surface: "#F3E3BF",
      text: "#4A3216",
      muted: "#7A5A2E",
      accent: "#B98B2E",
      accent2: "#8E5F2C",
      onAccent: "#FFFFFF",
      border: "rgba(255,255,255,0.75)",
      radius: "18px",
      shadow: "0 10px 28px -12px rgba(110,70,15,.5)",
      headerBg: "#F6EFE2",
      fontDisplay: "Playfair Display",
      fontBody: "Poppins",
    },
  },
  {
    // Modèle 14 : or rosé sur noir, bannières en dégradé rosé avec texte sombre
    id: "or-rose",
    name: "Or rosé",
    plan: "business",
    layout: "banners",
    buttonStyle: "gradient",
    header: "cover",
    avatarShape: "circle",
    dark: true,
    fonts: ["Cormorant+Garamond:wght@500;600;700", "Montserrat:wght@400;500;600;700"],
    tokens: {
      bg: "#0B0B0B",
      surface: "#1A1412",
      text: "#F5E6DD",
      muted: "#BFA79A",
      accent: "#E8B9A0",
      accent2: "#C98E72",
      onAccent: "#1B1210",
      border: "#3A2B25",
      radius: "20px",
      shadow: "none",
      headerBg: "linear-gradient(180deg,#3A2B25,#0B0B0B)",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Montserrat",
    },
  },
  {
    // Modèle 15 : noir et or, bannières sombres avec bouton doré
    id: "noir-or",
    name: "Noir & or",
    plan: "business",
    layout: "banners",
    buttonStyle: "soft",
    header: "cover",
    avatarShape: "circle",
    dark: true,
    uppercaseLinks: true,
    tracking: "0.06em",
    fonts: ["Montserrat:wght@500;600;700;800", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "radial-gradient(circle at 85% 20%,rgba(227,177,63,.25),transparent 40%),#050505",
      surface: "#15120C",
      text: "#FFFFFF",
      muted: "#C9C2B5",
      accent: "#E3B13F",
      accent2: "#B8860B",
      onAccent: "#1A1200",
      border: "#3A2E14",
      radius: "10px",
      shadow: "none",
      headerBg: "linear-gradient(180deg,#3A2E14,#050505)",
      fontDisplay: "Montserrat",
      fontBody: "Poppins",
    },
  },
  {
    // Modèle 18 : immobilier, bannières bleues arrondies sur fond gris clair
    id: "immobilier",
    name: "Immobilier",
    plan: "business",
    layout: "banners",
    buttonStyle: "gradient",
    header: "center",
    avatarShape: "circle",
    dark: false,
    fonts: ["Montserrat:wght@500;600;700;800", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "#E9EAEE",
      surface: "#FFFFFF",
      text: "#1B2433",
      muted: "#5D6677",
      accent: "#1F6FD0",
      accent2: "#174F9C",
      onAccent: "#FFFFFF",
      border: "#D9DCE3",
      radius: "20px",
      shadow: "0 8px 20px -10px rgba(23,79,156,.45)",
      headerBg: "#DDE3EE",
      fontDisplay: "Montserrat",
      fontBody: "Poppins",
    },
  },
  {
    // Modèle 12 : avocate, marine et crème, cartes à icônes + blocs stats / à propos / FAQ
    id: "avocate",
    name: "Avocate",
    plan: "business",
    layout: "cards",
    buttonStyle: "soft",
    header: "cover",
    avatarShape: "circle",
    dark: false,
    fonts: ["Playfair+Display:wght@500;600;700", "Inter:wght@400;500;600;700"],
    tokens: {
      bg: "#F6F0EA",
      surface: "#FFFFFF",
      text: "#1B2A4E",
      muted: "#5C6784",
      accent: "#1B2A4E",
      accent2: "#2C3F6E",
      onAccent: "#FFFFFF",
      border: "#E8E2DA",
      radius: "18px",
      shadow: "none",
      headerBg: "linear-gradient(180deg,#E9DDD0,#F6F0EA)",
      fontDisplay: "Playfair Display",
      fontBody: "Inter",
    },
  },
];