import type { Theme } from "./types";

// Plan GRATUIT : 4 thèmes simples, sans visuels lourds.
// Le 1er de la liste sert de repli quand un thème payant est verrouillé (voir registry.ts).
export const FREE_THEMES: Theme[] = [
  {
    // Modèle 5 : beige minimal, boutons pilule à contour, titres en capitales élégantes
    id: "sable",
    name: "Sable",
    plan: "free",
    layout: "pills",
    buttonStyle: "soft",
    header: "center",
    avatarShape: "circle",
    dark: false,
    uppercaseLinks: true,
    uppercaseName: true,
    tracking: "0.2em",
    fonts: ["Cormorant+Garamond:wght@500;600;700", "DM+Sans:wght@400;500;600"],
    tokens: {
      bg: "linear-gradient(180deg,#CFC6BC 0%,#E4DCD2 55%,#EFE9E1 100%)",
      surface: "rgba(244,238,231,0.72)",
      text: "#2B2420",
      muted: "#6B5F57",
      accent: "#2B2420",
      accent2: "#8A7A6E",
      onAccent: "#FFFFFF",
      border: "#4A413B",
      radius: "999px",
      shadow: "none",
      headerBg: "#CFC6BC",
      fontDisplay: "Cormorant Garamond",
      fontBody: "DM Sans",
    },
  },
  {
    // Modèle 4 : pastel rétro, avatar en blob, boutons rectangulaires à fine bordure
    id: "pop-retro",
    name: "Pop rétro",
    plan: "free",
    layout: "pills",
    buttonStyle: "soft",
    header: "center",
    avatarShape: "blob",
    dark: false,
    uppercaseLinks: true,
    tracking: "0.1em",
    fonts: ["Pacifico", "Outfit:wght@400;500;600"],
    tokens: {
      bg: "linear-gradient(180deg,#A9B4F4 0,#A9B4F4 120px,#FDF8EC 120px)",
      surface: "#CDD1FF",
      text: "#232323",
      muted: "#5C5C66",
      accent: "#232323",
      accent2: "#F7C6E0",
      onAccent: "#FFFFFF",
      border: "#232323",
      radius: "0px",
      shadow: "none",
      headerBg: "#A9B4F4",
      fontDisplay: "Pacifico",
      fontBody: "Outfit",
    },
  },
  {
    // Modèle 3 : noir profond, boutons pilule en dégradé rouge → orange
    id: "braise",
    name: "Braise",
    plan: "free",
    layout: "pills",
    buttonStyle: "gradient",
    header: "center",
    avatarShape: "circle",
    dark: true,
    uppercaseLinks: true,
    tracking: "0.04em",
    fonts: ["Roboto:wght@400;500;700;900"],
    tokens: {
      bg: "radial-gradient(circle at 85% 28%,#1E1E1E 0%,#0E0E0E 62%)",
      surface: "#1A1A1A",
      text: "#FFFFFF",
      muted: "#A3A3A3",
      accent: "#D40E00",
      accent2: "#E85D04",
      onAccent: "#FFFFFF",
      border: "#2A2A2A",
      radius: "999px",
      shadow: "0 8px 24px -10px rgba(232,93,4,.55)",
      headerBg: "#E85D04",
      fontDisplay: "Roboto",
      fontBody: "Roboto",
    },
  },
  {
    // Modèle 10 : fond blanc, arc sombre en haut, grille d'icônes 3 colonnes
    id: "cabinet",
    name: "Cabinet",
    plan: "free",
    layout: "grid",
    buttonStyle: "soft",
    header: "arc",
    avatarShape: "circle",
    dark: false,
    uppercaseLinks: true,
    tracking: "0.02em",
    fonts: ["Inter:wght@400;500;600;700;800"],
    tokens: {
      bg: "#FFFFFF",
      surface: "#FFFFFF",
      text: "#1D1D1D",
      muted: "#6B6B6B",
      accent: "#3A3434",
      accent2: "#5A5252",
      onAccent: "#FFFFFF",
      border: "#E6E6E6",
      radius: "14px",
      shadow: "none",
      headerBg: "#3B3737",
      fontDisplay: "Inter",
      fontBody: "Inter",
    },
  },
];