import type { Theme } from "./types";

// Plan PRO : cartes à icônes, styles verre / relief / contour, couleurs personnalisables.
export const PRO_THEMES: Theme[] = [
  {
    // Modèle 17 : rose poudré, cartes douces, première carte mise en avant
    id: "rose-poudre",
    name: "Rose poudré",
    plan: "pro",
    layout: "cards",
    buttonStyle: "soft",
    header: "center",
    avatarShape: "circle",
    dark: false,
    fonts: ["Playfair+Display:wght@500;600;700", "Inter:wght@400;500;600;700"],
    tokens: {
      bg: "#F4EEEA",
      surface: "#EADCD6",
      text: "#231C1A",
      muted: "#7A6A64",
      accent: "#A67C70",
      accent2: "#B8938A",
      onAccent: "#2B2321",
      border: "#E3D3CC",
      radius: "14px",
      shadow: "none",
      headerBg: "#EADCD6",
      fontDisplay: "Playfair Display",
      fontBody: "Inter",
    },
  },
  {
    // Modèle 6 : nude soyeux, cartes en relief (néomorphisme), en-tête avec photo de couverture
    id: "nude-soyeux",
    name: "Nude soyeux",
    plan: "pro",
    layout: "cards",
    buttonStyle: "neu",
    header: "cover",
    avatarShape: "circle",
    dark: false,
    fonts: ["Cormorant+Garamond:wght@500;600;700", "Inter:wght@400;500;600"],
    tokens: {
      bg: "linear-gradient(135deg,#F5ECE6,#F0E3DC)",
      surface: "#F8F2EE",
      text: "#5E4528",
      muted: "#8C7456",
      accent: "#8A6A45",
      accent2: "#B89B7A",
      onAccent: "#FFFFFF",
      border: "#EADFD7",
      radius: "26px",
      shadow: "0 10px 22px -10px rgba(120,86,60,.35), inset 0 1px 0 rgba(255,255,255,.85)",
      headerBg: "linear-gradient(135deg,#EAD9CC,#F5ECE6)",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Inter",
    },
  },
  {
    // Modèle 2 : vert sombre, cartes sobres, lien principal en dégradé vert
    id: "foret",
    name: "Forêt",
    plan: "pro",
    layout: "cards",
    buttonStyle: "soft",
    header: "cover",
    avatarShape: "circle",
    dark: true,
    fonts: ["Inter:wght@400;500;600;700;800"],
    tokens: {
      bg: "radial-gradient(ellipse at 50% -10%,#1E3B1F 0%,#0B140C 55%,#070D08 100%)",
      surface: "#0F1B11",
      text: "#F2F7EE",
      muted: "#9DB09A",
      accent: "#6CAF35",
      accent2: "#3F8B3A",
      onAccent: "#FFFFFF",
      border: "#223826",
      radius: "16px",
      shadow: "0 10px 30px -12px rgba(108,175,53,.45)",
      headerBg: "linear-gradient(180deg,#1A2E1B,#0B140C)",
      fontDisplay: "Inter",
      fontBody: "Inter",
    },
  },
  {
    // Modèle 16 : orange brillant, boutons pilule en verre
    id: "mandarine",
    name: "Mandarine",
    plan: "pro",
    layout: "pills",
    buttonStyle: "glass",
    header: "center",
    avatarShape: "circle",
    dark: true,
    fonts: ["Open+Sans:wght@400;600;700"],
    tokens: {
      bg: "linear-gradient(180deg,#F96A16 0%,#C24A0B 45%,#8E2A06 100%)",
      surface: "#A8451A",
      text: "#FFFFFF",
      muted: "#FFE1CC",
      accent: "#FFFFFF",
      accent2: "#FFD9B8",
      onAccent: "#7A2A05",
      border: "rgba(255,170,110,0.7)",
      radius: "999px",
      shadow: "0 8px 18px -6px rgba(0,0,0,.35)",
      headerBg: "#F96A16",
      fontDisplay: "Open Sans",
      fontBody: "Open Sans",
    },
  },
  {
    // Modèle 9 : noir et or, boutons à contour doré, lien principal en dégradé or
    id: "or-noir",
    name: "Or noir",
    plan: "pro",
    layout: "pills",
    buttonStyle: "outline",
    header: "center",
    avatarShape: "circle",
    dark: true,
    uppercaseName: true,
    fonts: ["Montserrat:wght@500;600;700;800", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "radial-gradient(circle at 90% 35%,rgba(212,160,23,.22),transparent 38%),#0A0A0A",
      surface: "#141414",
      text: "#E3B04B",
      muted: "#C9C2B5",
      accent: "#E8B33A",
      accent2: "#B8860B",
      onAccent: "#1A1200",
      border: "#E8B33A",
      radius: "14px",
      shadow: "none",
      headerBg: "#141414",
      fontDisplay: "Montserrat",
      fontBody: "Poppins",
    },
  },
  {
    // Modèle 8 : noir et bordeaux, boutons rectangulaires, affiche en couverture
    id: "opera",
    name: "Opéra",
    plan: "pro",
    layout: "pills",
    buttonStyle: "gradient",
    header: "cover",
    avatarShape: "rounded",
    dark: true,
    uppercaseLinks: true,
    tracking: "0.08em",
    fonts: ["Playfair+Display:wght@500;600;700", "Inter:wght@400;500;600;700"],
    tokens: {
      bg: "linear-gradient(180deg,#1A1A1A,#050505)",
      surface: "#141414",
      text: "#F5F5F5",
      muted: "#B5B5B5",
      accent: "#B01E1E",
      accent2: "#5E0808",
      onAccent: "#FFFFFF",
      border: "#2B2B2B",
      radius: "6px",
      shadow: "0 8px 20px -10px rgba(176,30,30,.6)",
      headerBg: "linear-gradient(180deg,#2A2A2A,#0B0B0B)",
      fontDisplay: "Playfair Display",
      fontBody: "Inter",
    },
  },
  {
    // Modèle 7 : blanc et vert, cartes à bordure noire, lien principal vert
    id: "vert-coach",
    name: "Coach vert",
    plan: "pro",
    layout: "cards",
    buttonStyle: "soft",
    header: "center",
    avatarShape: "circle",
    dark: false,
    uppercaseLinks: true,
    tracking: "0.02em",
    fonts: ["Montserrat:wght@500;600;700;800", "Poppins:wght@400;500;600"],
    tokens: {
      bg: "#F6F7F5",
      surface: "#FFFFFF",
      text: "#111111",
      muted: "#5F6B5C",
      accent: "#3FA535",
      accent2: "#2F8F2B",
      onAccent: "#FFFFFF",
      border: "#1A1A1A",
      radius: "10px",
      shadow: "none",
      headerBg: "#3FA535",
      fontDisplay: "Montserrat",
      fontBody: "Poppins",
    },
  },
];